const cors = require('cors')
const express = require('express')
const upload = require('multer')()
const dtd = require('./functions/dtd')
const index = require('./functions/form')
const format = require('./functions/format')
const schematron = require('./functions/schematron')

module.exports = express()
  .use(cors())
  .set('json spaces', 2)
  .get('/', index)
  .post('/format', upload.single('xml'), format)
  .post('/dtd', upload.single('xml'), dtd)
  .post('/schematron', upload.single('xml'), schematron)
